pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Nanipolabattula/thurrr-thurr.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('simple-node-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('simple-node-app') {
                    sh 'npm test || echo "No tests defined."'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('simple-node-app') {
                    echo '🚀 Deploying Node.js app...'
                    sh 'pm2 stop all || true'
                    sh 'pm2 start app.js'
                }
            }
        }
    }
}

